### PR TITLE
Typescript: Enable strict mode

### PR DESCRIPTION
**Pull request by torkelo**
Should fix some of the errors that show up when yarn linking into main repo

### CODE REVIEW

**Comment by dprokop** [comment]
hm, i see 94 errors when linking main and 94 errors when linking this branch. Are you sure this brings any improvement?

**Comment by Sergej-Vlasov** [comment]
same result here 94 errors before and after. Strict mode can be annoying with extra errors but no additional errors here so would be for enabling strict mode

**Comment by torkelo** [comment]
@dprokop well it fixes a few strict errors (see the ones fixed in PR) so it does something, not sure what else to enable

**Comment by torkelo** [comment]
@dprokop is there any argument to not extend tsconfig (Which has the important strict: true option)

**Comment by torkelo** [comment]
>  Strict mode can be annoying with extra errors but no additional errors here so would be for enabling strict mode
@Sergej-Vlasov not sure what your mean :)

**Comment by Sergej-Vlasov** [comment]
> > Strict mode can be annoying with extra errors but no additional errors here so would be for enabling strict mode
> 
> @Sergej-Vlasov not sure what your mean :)

Sorry, meant to say that I support enabling strict mode in short 😅

**Review by Sergej-Vlasov — APPROVED** [review]

**Pull request merged**
